version: '3.8'

services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - '8000:8000'
    environment:
      - PORT=8000
      - REDIS=redis://gntech_redis:6379
      - FIRESTORE_EMULATOR_HOST=firestore:8080
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_started
    networks:
      - challenge-network
      - firestore-network

  redis:
    image: redis:7
    container_name: gntech_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    networks:
      - challenge-network

  firestore:
    image: mtlynch/firestore-emulator
    ports:
      - "8080:8080"
      - "4000:4000"
    environment:
      - FIRESTORE_PROJECT_ID=demo-test
    volumes:
      - firestore-data:/data
    networks:
      - firestore-network

volumes:
  redisdata:
    driver: local
  firestore-data:
    driver: local

networks:
  challenge-network:
    driver: bridge
  firestore-network:
    driver: bridge